### ISSUE TITLE
snappy* temporary file ...

### ISSUE THREAD

**Issue by thyngum** [priesgo/leptospira-variant-calling#3]
Add a line in scvc preprocess_bam to delete the snappy*.so file created by Picard.

**Comment by priesgo** [comment]
Fixed.

To delete any temporary file from a wrapper use this API from the function self.build_pipeline(): 
self.add_temporary_file("%s/snappy*.so" % (self.output_folder))

**Comment by thyngum** [comment]
"To delete any temporary file from a wrapper use this API from the function
self.build_pipeline():
self.add_temporary_file("%s/snappy*.so" % (self.output_folder))"

No entendí nada but I'm impress .. with all the progress!

Estoy bastante descansado después de estas cortas vacaciones (creo) así que
espero poder meterle con fuerza a todo esto a partir de mañana ..

**Comment by priesgo** [comment]
Welcome back! Tómalo con calma a ver si te va a dar el síndrome
posvacacional ;)
